# Generated by Django 4.0 on 2022-02-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_certs', '0002_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
