# Generated by Django 4.0 on 2022-02-18 11:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_certs', '0003_alter_course_name_alter_staffmember_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['course', 'staff_member']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['name', 'email']},
        ),
        migrations.AlterModelManagers(
            name='certificate',
            managers=[
                ('certificates', django.db.models.manager.Manager()),
            ],
        ),
    ]
