# Generated by Django 4.0.3 on 2022-03-07 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_certs', '0004_alter_certificate_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('message_title', models.CharField(max_length=100)),
                ('message_body', models.TextField()),
                ('certificates', models.ManyToManyField(to='mentor_certs.certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_certs.course')),
            ],
            options={
                'ordering': ['start_time'],
            },
            managers=[
                ('mail_jobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MailJobCertificateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Failue'), (1, 'Success')], default=0)),
                ('log', models.TextField(null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_certs.certificate')),
                ('mail_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_certs.mailjob')),
            ],
        ),
    ]
