# Generated by Django 4.0.3 on 2022-03-08 10:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_certs', '0005_mailjob_mailjobcertificateresult'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('courses', django.db.models.manager.Manager()),
            ],
        ),
    ]
